name: API Call

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make API request and save response
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p api_responses
          curl -s "https://api.thecatapi.com/v1/images/search" -o api_responses/cat_image_$TIMESTAMP.json

      - name: Extract status code
        id: extract_status
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://api.thecatapi.com/v1/images/search)
          echo "STATUS_CODE=$STATUS_CODE" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Commit and push API response
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add api_responses/ || echo "No hay cambios en api_responses"
          git diff --cached --quiet || (git commit -m "Nueva llamada a la API - $TIMESTAMP" && git push origin master)

      - name: Send Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="GitHub Action ejecutada: API Call\nFecha y hora: ${{ env.TIMESTAMP }}\nRepositorio: ${{ github.repository }}\nCommit: ${{ github.sha }}\nResultado: ${{ env.STATUS_CODE }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="$MESSAGE"